package uk.gov.justice.digital.hmpps.hmppsstrengthsbasedneedsassessmentsapi.oasys.datamapping

enum class Field {
  ACCOMMODATION_PRACTITIONER_ANALYSIS_RELATED_TO_RISK,
  ACCOMMODATION_PRACTITIONER_ANALYSIS_RISK_OF_REOFFENDING,
  ACCOMMODATION_PRACTITIONER_ANALYSIS_RISK_OF_REOFFENDING_DETAILS,
  ACCOMMODATION_PRACTITIONER_ANALYSIS_RISK_OF_SERIOUS_HARM,
  ACCOMMODATION_PRACTITIONER_ANALYSIS_RISK_OF_SERIOUS_HARM_DETAILS,
  ACCOMMODATION_PRACTITIONER_ANALYSIS_STRENGTHS_OR_PROTECTIVE_FACTORS,
  ACCOMMODATION_PRACTITIONER_ANALYSIS_STRENGTHS_OR_PROTECTIVE_FACTORS_DETAILS,
  ASSESSMENT_COMPLETE,
  CURRENT_ACCOMMODATION,
  SUITABLE_HOUSING,
  SUITABLE_HOUSING_LOCATION,
  TEST_FIELD,
  TYPE_OF_TEMPORARY_ACCOMMODATION,
  ;

  val lower = name.lowercase()
}

enum class Value {
  NO,
  NO_ACCOMMODATION,
  SETTLED,
  SHORT_TERM,
  TEMPORARY,
  YES,
  YES_WITH_CONCERNS,
}
