package uk.gov.justice.digital.hmpps.hmppsstrengthsbasedneedsassessmentsapi.oasys.datamapping

enum class Field {
  ACCOMMODATION_PRACTITIONER_ANALYSIS_RISK_OF_REOFFENDING,
  ACCOMMODATION_PRACTITIONER_ANALYSIS_RISK_OF_SERIOUS_HARM,
  ASSESSMENT_COMPLETE,
  CURRENT_ACCOMMODATION,
  FINANCE_INCOME,
  FINANCE_MONEY_MANAGEMENT,
  SUITABLE_HOUSING,
  TEST_FIELD,
  ;

  val lower = name.lowercase()
}

enum class Value {
  BAD,
  CARERS_ALLOWANCE,
  DISABILITY_BENEFITS,
  EMPLOYMENT,
  FAIRLY_BAD,
  FAIRLY_GOOD,
  FAMILY_OR_FRIENDS,
  GOOD,
  NO,
  NO_ACCOMMODATION,
  NO_MONEY,
  OFFENDING,
  OTHER,
  PENSION,
  SETTLED,
  STUDENT_LOAN,
  TEMPORARY,
  Undeclared,
  WORK_RELATED_BENEFITS,
  YES,
  YES_WITH_CONCERNS,
}
