services:
  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - "5432:5432"

  hmpps-auth:
    ports:
      - "9090:9090"

  san-api:
    image: quay.io/hmpps/hmpps-strengths-based-needs-assessments-api:local
    build:
      target: development
    command: gradle --parallel --build-cache --configuration-cache bootRun
    volumes:
      - ./.git:/app/.git
      - ./.gradle:/home/gradle/.gradle
      - ./build:/app/build
      - ./src:/app/src
      - ./build.gradle.kts:/app/build.gradle.kts
      - ./settings.gradle.kts:/app/settings.gradle.kts
    ports:
      - "8080:8080"
      - "5005:5005"

  san-ui:
    ports:
      - "3000:3000"

  arns-handover:
    ports:
      - "7070:7070"

  oasys-ui:
    ports:
      - "7072:3000"

volumes:
  .gradle:
  build:
