services:
  api:
    image: quay.io/hmpps/hmpps-strengths-based-needs-assessments-api:${APP_VERSION:-latest}
    environment:
      LINK_BASE_URL: http://ui:3000/form

  ui:
    environment:
      INGRESS_URL: http://ui:3000
      HMPPS_AUTH_EXTERNAL_URL: http://hmpps-auth:9090/auth

volumes:
  test_results:
