version: "3.8"
services:
  api:
    image: quay.io/hmpps/hmpps-strengths-based-needs-assessments-api:local
    build:
      target: development
    command: gradle --parallel --build-cache --configuration-cache bootRun
    volumes:
      - ./.git:/app/.git
      - ./.gradle:/home/gradle/.gradle
      - ./build:/app/build
      - ./src:/app/src
      - ./build.gradle.kts:/app/build.gradle.kts
      - ./settings.gradle.kts:/app/settings.gradle.kts
    ports:
      - "8080:8080"
      - "5005:5005"

  ui:
    ports:
      - "3000:3000"

volumes:
  .gradle:
  build:
