version: "3"
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    networks:
      - hmpps
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  hmpps-strengths-based-needs-assessments-api:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-strengths-based-needs-assessments-api
    depends_on:
     - postgres
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

networks:
  hmpps:
