version: "3.8"
services:
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hmpps-auth:9090/auth/health"]
    environment:
      SERVER_PORT: 9090
      SPRING_PROFILES_ACTIVE: dev
      APPLICATION_AUTHENTICATION_UI_ALLOWLIST: 0.0.0.0/0
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG

  postgres:
    image: postgres:16
    networks:
      - hmpps
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  api:
    image: quay.io/hmpps/hmpps-strengths-based-needs-assessments-api:latest
    build:
      context: .
    networks:
      - hmpps
    depends_on:
     - postgres
     - hmpps-auth
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8080/health/ping"]
      interval: 5s
      retries: 100
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev,postgres
      DATABASE_ENDPOINT: postgres:5432
      OAUTH_ENDPOINT_URL: http://hmpps-auth:9090/auth
      LINK_BASE_URL: http://localhost:3000/form
      FORM_CONFIG_BASE_URL: http://ui:3000/form

networks:
  hmpps:
