services:
  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - "5432:5432"

  san-api:
    image: ghcr.io/ministryofjustice/hmpps-strengths-based-needs-assessments-api:local
    build:
      target: development
    command: gradle --parallel --build-cache --configuration-cache --info bootRun
    volumes:
      - ./.git:/app/.git
      - ./.gradle:/home/gradle/.gradle
      - ./build:/app/build
      - ./src:/app/src
      - ./build.gradle.kts:/app/build.gradle.kts
      - ./settings.gradle.kts:/app/settings.gradle.kts
    ports:
      - "8080:8080"
      - "5005:5005"

volumes:
  .gradle:
  build:
