version: "3"
services:
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-strengths-based-needs-assessments-api-auth
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/auth/health"]
    environment:
      - SERVER_PORT=9090
      - SPRING_PROFILES_ACTIVE=dev

  postgres:
    image: postgres:14
    networks:
      - hmpps
    container_name: hmpps-strengths-based-needs-assessments-api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  hmpps-strengths-based-needs-assessments-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: hmpps-strengths-based-needs-assessments-api
    depends_on:
     - postgres
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: "dev,postgres"
      DATABASE_ENDPOINT: "postgres:5432"

networks:
  hmpps:
