#!/usr/bin/env bash
# Restores every per-shard database dump into the local postgres container, remapping
# each shard's integer primary/foreign key values into their own non-overlapping block -
# a local equivalent of the e2e_test workflow's "combine-db-dumps" CI job.
#
# Each shard was generated by an *independent* Postgres instance (one per parallel
# e2e-test matrix job), so only `uuid` columns are globally unique across shards -
# every SERIAL/IDENTITY integer id restarts at 1 in every shard. Restoring them
# directly on top of each other hits primary key collisions, so instead: restore one
# shard's data at a time, then shift that shard's just-restored integer key columns
# (discovered generically from the schema's own primary/foreign key constraints, so
# this doesn't need to hardcode table names from schemas we don't own the source of,
# e.g. the coordinator schema) by a per-shard offset, before restoring the next shard.
#
# DUMPS_DIR may contain the raw db_dump_N.zip files as downloaded from the GitHub Actions
# UI (each holding a single db_dump.dump), already-unzipped db_dump.dump files, or a mix.
#
# Usage: combine_db_dumps.sh <dumps-dir>

set -eu

DUMPS_DIR="${1:?Usage: combine_db_dumps.sh <dumps-dir>}"
PROJECT_NAME="hmpps-assess-risks-and-needs"
CONTAINER="${PROJECT_NAME}-postgres-1"

# Generous headroom: real per-shard row counts are tiny (test data), so any offset/
# threshold far above that is safe. Must stay equal to each other (see below).
OFFSET_STEP=100000000
THRESHOLD=100000000

if ! docker ps --format '{{.Names}}' | grep -qx "${CONTAINER}"; then
  echo "The postgres container (${CONTAINER}) isn't running - start it first with 'make up' or 'make migrator-up'." >&2
  exit 1
fi

psql() { docker exec -i "${CONTAINER}" psql -U root -d postgres -v ON_ERROR_STOP=1 "$@"; }

WORK_DIR=$(mktemp -d)
trap 'rm -rf "${WORK_DIR}"' EXIT

shopt -s nullglob
zips=("${DUMPS_DIR}"/*.zip)
shopt -u nullglob

if [ "${#zips[@]}" -gt 0 ]; then
  echo "Unzipping ${#zips[@]} artifact zip(s) from ${DUMPS_DIR}..."
  for zip in "${zips[@]}"; do
    unzip -q -o "${zip}" -d "${WORK_DIR}/$(basename "${zip}" .zip)"
  done
fi

# Also pick up any dumps that are already unzipped directly under DUMPS_DIR.
dumps=$( { find "${WORK_DIR}" -name '*.dump'; find "${DUMPS_DIR}" -name '*.dump'; } | sort -V)

if [ -z "${dumps}" ]; then
  echo "No .dump files found under ${DUMPS_DIR}" >&2
  exit 1
fi

TOTAL=$(echo "${dumps}" | grep -c .)

first=$(echo "${dumps}" | head -n1)
echo "Restoring schema from ${first}"
docker exec -i "${CONTAINER}" pg_restore --schema-only --clean --if-exists --no-owner --no-privileges -U root -d postgres < "${first}"

echo "Discovering integer primary/foreign key columns to remap..."

# Every column participating in a PK or FK constraint, on any integer type, excluding
# Flyway's own bookkeeping table (its rows are identical across shards and are kept
# from the first shard only - see --exclude-table-data below).
KEY_COLUMNS=$(psql -tA -F'|' -c "
  SELECT DISTINCT tc.table_schema, tc.table_name, kcu.column_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
  JOIN information_schema.columns c
    ON c.table_schema = kcu.table_schema AND c.table_name = kcu.table_name AND c.column_name = kcu.column_name
  WHERE tc.constraint_type IN ('PRIMARY KEY', 'FOREIGN KEY')
    AND tc.table_schema NOT IN ('pg_catalog', 'information_schema')
    AND tc.table_name <> 'flyway_schema_history'
    AND c.data_type IN ('smallint', 'integer', 'bigint');
")

# Just the primary keys, so sequences can be resynced once at the end.
PK_COLUMNS=$(psql -tA -F'|' -c "
  SELECT DISTINCT tc.table_schema, tc.table_name, kcu.column_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
  WHERE tc.constraint_type = 'PRIMARY KEY'
    AND tc.table_schema NOT IN ('pg_catalog', 'information_schema')
    AND tc.table_name <> 'flyway_schema_history';
")

TABLES=$(echo "${KEY_COLUMNS}" | awk -F'|' '{print $1"|"$2}' | sort -u)

echo "Found $(echo "${KEY_COLUMNS}" | grep -c .) key column(s) across $(echo "${TABLES}" | grep -c .) table(s)."

COUNT=0
for dump in ${dumps}; do
  COUNT=$((COUNT + 1))
  echo "[${COUNT}/${TOTAL}] Restoring data from ${dump}"

  if [ "${COUNT}" -gt 1 ]; then
    # pg_restore has no --exclude-table-data (that's a pg_dump-only flag), so skip
    # flyway_schema_history's data by filtering it out of the archive's TOC list -
    # every shard's copy is identical (same migrations, same app build), so only
    # the first shard's copy needs restoring.
    TOC_FILE="${WORK_DIR}/toc_${COUNT}.list"
    docker exec -i "${CONTAINER}" pg_restore -l < "${dump}" \
      | grep -v 'TABLE DATA .* flyway_schema_history ' > "${TOC_FILE}"
    docker cp "${TOC_FILE}" "${CONTAINER}:/tmp/toc_${COUNT}.list"
    docker exec -i "${CONTAINER}" pg_restore --data-only --disable-triggers --no-owner --no-privileges \
      -L "/tmp/toc_${COUNT}.list" -U root -d postgres < "${dump}"
    docker exec "${CONTAINER}" rm -f "/tmp/toc_${COUNT}.list"
  else
    docker exec -i "${CONTAINER}" pg_restore --data-only --disable-triggers --no-owner --no-privileges \
      -U root -d postgres < "${dump}"
  fi

  OFFSET=$((COUNT * OFFSET_STEP))
  echo "Remapping shard ${COUNT}'s ids by +${OFFSET}..."

  {
    echo "BEGIN;"
    while IFS='|' read -r schema table; do
      [ -z "${schema}" ] && continue
      echo "ALTER TABLE \"${schema}\".\"${table}\" DISABLE TRIGGER ALL;"
    done <<< "${TABLES}"

    while IFS='|' read -r schema table column; do
      [ -z "${schema}" ] && continue
      echo "UPDATE \"${schema}\".\"${table}\" SET \"${column}\" = \"${column}\" + ${OFFSET} WHERE \"${column}\" < ${THRESHOLD} AND \"${column}\" IS NOT NULL;"
    done <<< "${KEY_COLUMNS}"

    while IFS='|' read -r schema table; do
      [ -z "${schema}" ] && continue
      echo "ALTER TABLE \"${schema}\".\"${table}\" ENABLE TRIGGER ALL;"
    done <<< "${TABLES}"
    echo "COMMIT;"
  } | psql
done

echo "Resetting sequences so future inserts don't clash with remapped ids..."

{
  while IFS='|' read -r schema table column; do
    [ -z "${schema}" ] && continue
    echo "SELECT setval(pg_get_serial_sequence('\"${schema}\".\"${table}\"', '${column}'), COALESCE((SELECT MAX(\"${column}\") FROM \"${schema}\".\"${table}\"), 1))"
    echo "  WHERE pg_get_serial_sequence('\"${schema}\".\"${table}\"', '${column}') IS NOT NULL;"
  done <<< "${PK_COLUMNS}"
} | psql

echo "Done. Restored and remapped data from ${TOTAL} shard(s) into ${CONTAINER}."
