package uk.gov.justice.digital.hmpps.hmppsstrengthsbasedneedsassessmentsapi.migrator.mappers

class QuestionCodeMapper {
  companion object {
    val overrides = mapOf(
      "accommodation_is_current_accommodation_user_submitted" to "is_user_submitted_accommodation_status",
      "accommodation_is_settled_accommodation_user_submitted" to "is_user_submitted_accommodation_details",
      "accommodation_is_temporary_accommodation_user_submitted" to "is_user_submitted_accommodation_details",
      "accommodation_is_temporary_accommodation_cas_ap_user_submitted" to "is_user_submitted_accommodation_details",
      "accommodation_is_no_accommodation_user_submitted" to "is_user_submitted_accommodation_details",
      "accommodation_is_accommodation_summary_user_submitted" to "is_user_submitted_accommodation_summary",
      "employment_education_is_current_employment_user_submitted" to "is_user_submitted_employment_status",
      "employment_education_is_employed_user_submitted" to "is_user_submitted_employment_education_details",
      "employment_education_is_retired_user_submitted" to "is_user_submitted_employment_education_details",
      "employment_education_is_employed_before_user_submitted" to "is_user_submitted_employment_education_details",
      "employment_education_is_never_employed_user_submitted" to "is_user_submitted_employment_education_details",
      "employment_education_is_employment_education_summary_user_submitted" to "is_user_submitted_employment_education_summary",
      "finance_is_finance_user_submitted" to "is_user_submitted_finance",
      "finance_is_finance_summary_user_submitted" to "is_user_submitted_finance_summary",
      "drug_use_is_drug_use_user_submitted" to "is_user_submitted_drug_use_status",
      "drug_use_is_add_drugs_user_submitted" to "is_user_submitted_drug_use_types",
      "drug_use_is_drug_details_user_submitted" to "is_user_submitted_drug_use_details",
      "drug_use_is_drug_details_injected_user_submitted" to "is_user_submitted_drug_use_details",
      "drug_use_is_drug_details_more_than_six_months_user_submitted" to "is_user_submitted_drug_use_details",
      "drug_use_is_drug_details_more_than_six_months_injected_user_submitted" to "is_user_submitted_drug_use_details",
      "drug_use_is_drug_use_history_user_submitted" to "is_user_submitted_drug_use_history",
      "drug_use_is_drug_use_history_more_than_six_months_user_submitted" to "is_user_submitted_drug_use_history",
      "drug_use_is_drug_use_summary_user_submitted" to "is_user_submitted_drug_use_summary",
      "alcohol_use_is_alcohol_user_submitted" to "is_user_submitted_alcohol_use_status",
      "alcohol_use_is_alcohol_use_last_three_months_user_submitted" to "is_user_submitted_alcohol_use_details",
      "alcohol_use_is_alcohol_use_less_three_months_user_submitted" to "is_user_submitted_alcohol_use_details",
      "alcohol_use_is_alcohol_use_summary_user_submitted" to "is_user_submitted_alcohol_use_summary",
      "health_wellbeing_is_health_wellbeing_user_submitted" to "is_user_submitted_health_wellbeing_status",
      "health_wellbeing_is_physical_mental_health_user_submitted" to "is_user_submitted_health_wellbeing_details",
      "health_wellbeing_is_physical_health_user_submitted" to "is_user_submitted_health_wellbeing_details",
      "health_wellbeing_is_mental_health_user_submitted" to "is_user_submitted_health_wellbeing_details",
      "health_wellbeing_is_no_physical_mental_health_user_submitted" to "is_user_submitted_health_wellbeing_details",
      "health_wellbeing_is_health_wellbeing_summary_user_submitted" to "is_user_submitted_health_wellbeing_summary",
      "thinking_behaviours_attitudes_is_thinking_behaviours_attitudes_user_submitted" to "is_user_submitted_thinking_behaviours_attitudes",
      "thinking_behaviours_attitudes_is_thinking_behaviours_attitudes_risk_of_sexual_harm_user_submitted" to "is_user_submitted_thinking_behaviours_attitudes_risk_of_sexual_harm",
      "thinking_behaviours_attitudes_is_thinking_behaviours_attitudes_risk_of_sexual_harm_details_user_submitted" to "is_user_submitted_thinking_behaviours_attitudes_risk_of_sexual_harm_details",
      "thinking_behaviours_attitudes_is_thinking_behaviours_attitudes_summary_user_submitted" to "is_user_submitted_thinking_behaviours_attitudes_summary",
      "personal_relationships_community_is_personal_relationships_children_information_user_submitted" to "is_user_submitted_personal_relationships_children_information",
      "personal_relationships_community_is_personal_relationships_user_submitted" to "is_user_submitted_personal_relationships",
      "personal_relationships_community_is_personal_relationships_community_user_submitted" to "is_user_submitted_personal_relationships_community",
      "personal_relationships_community_is_personal_relationships_children_user_submitted" to "is_user_submitted_personal_relationships",
      "personal_relationships_community_is_personal_relationships_community_summary_user_submitted" to "is_user_submitted_personal_relationships_community_summary",
      "offence_analysis_is_offence_analysis_user_submitted" to "is_user_submitted_offence_analysis",
      "offence_analysis_is_offence_analysis_victim_details_user_submitted" to "is_user_submitted_offence_analysis_victim_summary",
      "offence_analysis_is_offence_analysis_involved_parties_user_submitted" to "is_user_submitted_offence_analysis_involved_parties",
      "offence_analysis_is_offence_analysis_impact_user_submitted" to "is_user_submitted_offence_analysis_impact",
      "offence_analysis_is_offence_analysis_impact_others_involved_user_submitted" to "is_user_submitted_offence_analysis_impact",
    )

    fun getCodeFor(questionCode: String) = overrides[questionCode] ?: questionCode
  }
}
