---
# Per environment values which override defaults in hmpps-strengths-based-needs-assessments-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: api.strengths-based-needs-test.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    FORM_CONFIG_BASE_URL: https://strengths-based-needs-assessments-test.hmpps.service.justice.gov.uk/config

  allowlist:
    mp-nat-egress-one: 13.43.9.198/32
    mp-nat-egress-two: 13.42.163.245/32
    mp-nat-egress-three: 18.132.208.127/32    
    nat-gw-one: 35.178.209.113/31
    nat-gw-two: 3.8.51.207/31
    nat-gw-three: 35.177.252.54/31
    capita-dev: 51.104.16.30/31
    captia-further: 172.167.141.40/32
    neil-test: 51.155.102.238/32
    capita-developers-vms-one: 85.115.52.180/32
    capita-developers-vms-two: 85.115.52.200/29
    capita-developers-vms-three: 85.115.53.180/32
    capita-developers-vms-four: 85.115.53.200/29
    capita-developers-vms-five: 85.115.54.180/32
    capita-developers-vms-six: 85.115.54.200/29
    oasys-box-t2 : 10.26.12.211/32
    krupal-appsec: 80.195.27.199/32
    

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-strengths-based-needs-assessments

dataExtractor:
  enabled: true
