---
# Per environment values which override defaults in hmpps-strengths-based-needs-assessments-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: api.strengths-based-needs-dev.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    FORM_CONFIG_BASE_URL: https://strengths-based-needs-assessments-dev.hmpps.service.justice.gov.uk/config
    SPRING_PROFILES_ACTIVE: "logstash, postgres, dev"

  allowlist:
    capita-dev: 51.104.16.30/31
    captia-further: 172.167.141.40/32
    neil-test: 51.155.102.238/32
    capita-developers-vms-one: 85.115.52.180/32
    capita-developers-vms-two: 85.115.52.200/29
    capita-developers-vms-three: 85.115.53.180/32
    capita-developers-vms-four: 85.115.53.200/29
    capita-developers-vms-five: 85.115.54.180/32
    capita-developers-vms-six: 85.115.54.200/29
    joel-app-sec-1: 100.64.10.206/32
    joeal-app-sec-2: 86.134.133.78/32

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-strengths-based-needs-assessments

dataExtractor:
  enabled: true
