---
# Per environment values which override defaults in hmpps-strengths-based-needs-assessments-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: api.strengths-based-needs-dev.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    LINK_BASE_URL: https://strengths-based-needs-assessments-dev.hmpps.service.justice.gov.uk/form
    FORM_CONFIG_BASE_URL: https://strengths-based-needs-assessments-dev.hmpps.service.justice.gov.uk/form

  allowlist:
    capita-dev: 51.104.16.30/31

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-strengths-based-needs-assessments

dataExtractor:
  enabled: true
