name: Run end-to-end tests

on:
  workflow_call:
    inputs:
      app_version:
        description: App version
        required: true
        type: string

permissions:
  contents: read

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${{ inputs.app_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: build_image
          path: ${{ runner.temp }}

      - name: Load image
        run: docker load --input ${{ runner.temp }}/build_image.tar

      - name: Stand up a test environment
        run: make test-up

      - name: Clone UI repository
        uses: actions/checkout@v4
        with:
          repository: ministryofjustice/hmpps-strengths-based-needs-assessments-ui
          path: e2e-test-ui

      - name: Run the end-to-end tests
        run: |
          cd e2e-test-ui
          make e2e-ci

      - name: Export container logs
        if: failure()
        run: make save-logs OUTPUT_LOGS_DIR=${{ runner.temp }}/docker-logs PROJECT_NAME="hmpps-assess-risks-and-needs-test"

      - name: Upload test results
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: e2e_test_results
          path: |
            e2e-test-ui/test_results
            e2e-test-ui/cypress/screenshots
            ${{ runner.temp }}/docker-logs
